### PR TITLE
Bumped reccommended LND version

### PR DESCRIPTION
**Pull request by rstmsn**
Bumped reccommended LND version to 0.15.4-beta

### CODE REVIEW

**Review by guggero — CHANGES_REQUESTED** [review]
Thanks for flagging this outdated sentence. The minimum required version [was bumped to `v0.15.1-beta`](https://github.com/lightninglabs/pool/blob/master/server.go#L43) a while back, so the first part of the sentence should also be updated. Maybe we can even link to the section in the code so it's easier to check?

**Comment by rstmsn** [comment]
> Thanks for flagging this outdated sentence. The minimum required version [was bumped to `v0.15.1-beta`](https://github.com/lightninglabs/pool/blob/master/server.go#L43) a while back, so the first part of the sentence should also be updated. Maybe we can even link to the section in the code so it's easier to check?

Would you agree that it would make more sense to also bump the minimum required version in the code to 0.15.4-beta, as this is the update that patches the large taproot transaction bug ?
Presumably loop will fail to run if it's operating on top of an lnd that is not patched for this issue?

Grateful for thoughts in case I have overlooked something.

**Comment by guggero** [comment]
> Would you agree that it would make more sense to also bump the minimum required version in the code to 0.15.4-beta, as this is the update that patches the large taproot transaction bug ?

Yes, I think that makes sense.

**Comment by guggero** [comment]
Replaced by https://github.com/lightninglabs/pool/pull/435.

**Pull request closed without merging**
